Dev
Marat1905/Airports pull request #1
Opened 2023-03-06 16:25 UTC by Marat1905

Отпрака на проверку

2023-04-25 05:53 UTC, Infarh requested changes

2023-04-25 05:53 UTC, Infarh commented on Data/Airports.Data/ReadAirportsCsv.cs
> +        }
```suggestion
        public IEnumerable<ZipArchiveEntry> ReadZip()
        {
            //Проверяем правильность указания пути к архиву.
            FileInfo file = new FileInfo(ZipPath);
            if (!file.Exists)
                throw new FileNotFoundException("Не правильно указан путь к архиву", ZipPath);
            //Получаем список файлов в архиве
            using (ZipArchive archive = ZipFile.OpenRead(ZipPath))
                foreach(var entry in archive.Entries)
                    yield return entry;
        }
```

2023-04-25 05:53 UTC, Infarh commented on Data/Airports.Data/ReadAirportsCsv.cs
> +        public IEnumerable<T> GetCsv<T>(string fileName, string separator = ",") where T : class, new()
Этот метод слишком сложный. Его надо распилить на части. 
Нужно внутри него выделить логические блоки и оформить их в виде отдельных методов.

2023-04-25 05:53 UTC, Infarh commented on Data/Airports.Data/ReadAirportsCsv.cs
> +                                yield return result;
👍

2023-04-25 05:53 UTC, Infarh commented on Data/Airports.DataTests/ReadAirportsCsvTests.cs
> +        string zipPath = @"C:\Users\Marat\Downloads\Airports.zip";
👎 Не используйте глобальные пути. На другом компьютере этого файла не будет, и тест не сработает. Файл надо приложить к проекту в репозиторий и использовать локальный путь к нему в рамках репозитория.

2023-04-25 05:53 UTC, Infarh commented on Tests/TestConsole/Program.cs
> +string zipPath = @"C:\Users\Marat\Downloads\Airports.zip";
Аналогичная проблема.

2023-04-30 11:40 UTC, Marat1905 commented
Объединяемся

2023-04-30 11:57 UTC, merged